/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.vistas;

import com.utilidades.CreacionMapa;
import java.awt.BorderLayout;
import javax.swing.JFrame;
import javax.swing.WindowConstants;

/**
 * Nombre del Formulario: FrmGenerarMapa
 * Fecha: 0/11/2020 
 * CopyRight: Pedro Campos
 * modificación:05/11/2020 
 * Version: 1.1
 * @author pedro
 */
public class FrmGenerarMapa extends javax.swing.JInternalFrame {

    public double latitud;
    public double longitud;
    public String nombre;
    public boolean modificacion;
    
    public FrmGenerarMapa(boolean modify, double lang, double longi, String name) {
        initComponents();
        latitud = lang;
        longitud = longi;
        nombre = name;
        modificacion = modify;
        generarMapa();
    }

    public void generarMapa(){
        final CreacionMapa sample = new CreacionMapa();
        if(modificacion){
            sample.latitud = (latitud);
            sample.longitud = (longitud);
            sample.nombre = (nombre);
            sample.modificacion = (modificacion);
        }else{
            sample.latitud = (13.794185);
            sample.longitud = (-88.89653);
            sample.nombre = ("");
        }
        
        JFrame frame = new JFrame("Mapa");
    
        frame.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        frame.add(sample, BorderLayout.CENTER);
        frame.setSize(700, 500);
        frame.setLocationRelativeTo(null);
        frame.setExtendedState(JFrame.MAXIMIZED_BOTH);
        frame.setVisible(true);
        sample.setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
